#!/bin/bash

################ DIRECTORIES
SC3_HOME="/home/kiwi/seiscomp3"
KIWI_HOME="$SC3_HOME/KIWISC3"
RESP="$KIWI_HOME/RESP"
DATA="$SC3_HOME/data"

################ CONFIG
Country="Iran"
HOST="192.168.127.68"  # SC3 Host address
length_lim=100         # Length limit for data deletion
MAGLIM=4.2			   # Magnitude limit
TIME1=10		 	   # End time 
TIME2=20	     	   # Start time 
sleep=`echo "($TIME2 - $TIME1) * 60" | bc -l`
	


GET_EVE_INFO ()
{
	# Get all eventIDs within the given time range from $HOST host
	read -a EVEIDS <<< `seiscomp exec scevtls -d mysql://sysop:sysop@"$HOST"/seiscomp3 --begin "$T2" --end "$T1"`
	[ -z ${EVEIDS[0]} ] && echo -e "Time Range = $T2 to $T1\nNo. Events = 0\nSleeping! ..." && 
		echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#" && continue
		
	for EVID in "${EVEIDS[@]}"; do
		# Get the EQ information for eventID $EVID
		seiscomp exec scbulletin -E $EVID -3 -d mysql://sysop:sysop@"$HOST"/seiscomp3 > .EVE_INFO.txt
		
		EVEMAG=`grep -w "preferred" .EVE_INFO.txt | awk '{print $2}'`
		
		if [ -z "$EVEMAG" ]; then
			EVEMAG=`grep -w "MLv" .EVE_INFO.txt | awk '{print $2}' | head -1`
		elif [ -z "$EVEMAG" ]; then
			EVEMAG=`grep -w "ML" .EVE_INFO.txt | awk '{print $2}' | head -1`
		elif [ -z "$EVEMAG" ]; then
			EVEMAG=`grep -w "Mw(mB)" .EVE_INFO.txt | awk '{print $2}' | head -1`
		elif [ -z "$EVEMAG" ]; then
			EVEMAG=`grep -w "mB" .EVE_INFO.txt | awk '{print $2}' | head -1`		
		fi	
		
		EVELA=`grep -w "Latitude" .EVE_INFO.txt | awk '{print $2}'`
		EVELO=`grep -w "Longitude" .EVE_INFO.txt | awk '{print $2}'`	
		EVE_DEP=`grep -w "Depth" .EVE_INFO.txt | awk '{print $2}'`	
		
		# Select the proper Sampling Rate and maximum depth based on the GFDB used
		SW1=`echo "$EVELA >= 27.6" | bc -l`
		SW2=`echo "$EVELA <= 32.0" | bc -l`
		SW3=`echo "$EVELO >= 47.0" | bc -l`
		SW4=`echo "$EVELO <= 53.0" | bc -l`
	
		TH1=`echo "$EVELA >= 34.5" | bc -l`
		TH2=`echo "$EVELA <= 37.0" | bc -l`
		TH3=`echo "$EVELO >= 49.5" | bc -l`
		TH4=`echo "$EVELO <= 53.5" | bc -l`
	
		if [ "$SW1" -eq "1" ] && [ "$SW2" -eq "1" ] && [ "$SW3" -eq "1" ] && [ "$SW4" -eq "1" ]; then
			DEC=2
			MAX_DEP="60"
			freql=(0.005 0.008 0.8 0.9)
		elif [ "$TH1" -eq "1" ] && [ "$TH2" -eq "1" ] && [ "$TH3" -eq "1" ] && [ "$TH4" -eq "1" ]; then
			DEC=10
			MAX_DEP="35"
			freql=(0.005 0.008 4.0 4.5)
		else
			DEC=2
			MAX_DEP="60"
			freql=(0.005 0.008 0.8 0.9)
		fi
		
		# Event limits to be considered
		C1=$(( `echo "$EVEMAG < $MAGLIM" | bc -l` ))
		C2=$(( `echo "$EVE_DEP >= $MAX_DEP" | bc -l` )) 
		
		if [[ -n `grep -i "$Country" .EVE_INFO.txt` ]] || [[ -n `grep -i "Caspian Sea" .EVE_INFO.txt` ]]; then
			[ "$C1" -eq "1" ] && echo "Event ($EVID) is smaller than $MAGLIM. Ignored ..." && continue
			[ "$C2" -eq "1" ] && echo "Event ($EVID) is located Deeper than our Greens Functions Depth limit. Ignored ... " && continue
			echo -e "Processing EventID  #~~~~~~~~ $EVID ~~~~~~~~#"
			
			EVE_DTE=`grep -w "Date" .EVE_INFO.txt | awk '{print $2}'`
			EVE_TME=`grep -w "Time" .EVE_INFO.txt | awk '{print $2}'`
			EVE_RMS=`grep -w "Residual RMS" .EVE_INFO.txt | awk '{print $3}'`
			EVE_GAP=`grep -w "Azimuthal gap" .EVE_INFO.txt | awk '{print $3}'`
			EVMAG_T=`grep -w "preferred" .EVE_INFO.txt | awk '{print $1}'`
		
			YEAR=${EVE_DTE%%-*}
			JD=`date -d "$EVE_DTE" +%j`
			
			# Setting Time window length based on MAX_DIS values in SOURCE_ANALYSIS script And the equation (0.36 * Dist) + 60  ...
		
			if (( `echo "$EVEMAG >= 4.00" | bc -l` )) && (( `echo "$EVEMAG < 4.60" | bc -l` )) ; then					
				TINC=260
			elif (( `echo "$EVEMAG >= 4.60" | bc -l` )) && (( `echo "$EVEMAG < 5.00" | bc -l` )) ; then							
				TINC=280
			elif (( `echo "$EVEMAG >= 5.00" | bc -l` )) && (( `echo "$EVEMAG < 5.60" | bc -l` )) ; then							
				TINC=310
			elif (( `echo "$EVEMAG >= 5.60" | bc -l` )) && (( `echo "$EVEMAG < 6.00" | bc -l` )) ; then							
				TINC=450
			elif (( `echo "$EVEMAG >= 6.00" | bc -l` )) && (( `echo "$EVEMAG < 7.00" | bc -l` )) ; then						
				TINC=560
			else
				TINC=600
			fi			
							
			# Station selection based on stations used by sc3 for picking (stations with valid SNR)
		
			SL=`grep -win "Phase arrivals" .EVE_INFO.txt | cut -f 1 -d ":"` && L1=$(( SL + 2 ))
			EL=`grep -win "Station magnitudes" .EVE_INFO.txt | cut -f 1 -d ":"` && L2=$(( EL - 2 ))
			awk "NR >= $L1 && NR <= $L2 {print}" .EVE_INFO.txt | awk '{print $1}' > .selected_st.txt
			
			
			echo "################## STATIONS TO BE USED ##################"
			cat .selected_st.txt
			echo "#########################################################"	
			
			echo "The Data Length will be $TINC seconds."
			echo "All data will Decimate to $DEC SPS."
			
			DATA_PATH="DATA/$EVE_DTE-$EVE_TME-$EVELA-$EVELO-$EVE_DEP-$EVEMAG"
							
			TMAX=`date -d "$EVE_DTE $EVE_TME $TINC seconds" "+%Y-%m-%d %H:%M:%S"`
			
			[ ! -d "$DATA_PATH" ] && mkdir -p "$DATA_PATH" || rm -f $DATA_PATH/* 2> /dev/null			
			
			# JACKSEIS, Extract and Decimate the Data
			cat .selected_st.txt | while read STA; do
				[ `find $DATA/"$YEAR"/ -type f -name "*$STA*.D.$YEAR.$JD" | wc -l` -eq 0 ] && continue
				find $DATA/"$YEAR"/ -type f -name "*$STA*.D.$YEAR.$JD" | xargs jackseis --tmin="$EVE_DTE $EVE_TME" \
				--tmax="$TMAX" --downsample="$DEC" --debug --output-dir="$DATA_PATH" --output-format="sac" --output=%n.%s.%l.%c.SAC 2> /dev/null
			done
			
			mkdir "$DATA_PATH"/DISP 
			cp .selected_st.txt	$DATA_PATH/DISP/.stations.dat
			
			# Deconvolution process
			echo -e "\nProgram started Deconvolution Process."
			
			cd "$DATA_PATH"
			for data in `ls *SAC`; do
				B=`saclst B f $data | awk '{print $2}'`
				E=`saclst E f $data | awk '{print $2}'`
				(( `echo "$E - $B < $length_lim" | bc -l` )) && rm "$data" && continue
				RESPE=RESP."${data%.*}"
				sac <<- EOF
				r $data
				rtr; rmean; taper
				echo on
				transfer from evalresp fname $RESP/$RESPE to none freql ${freql[@]}
				echo off
				div 1e9
				w TR.$data
				q
				EOF
			done
			
			jackseis ./TR.*SAC --output-dir="./DISP/" --output-format="mseed" --output=DISPL.%n.%s.%l.%c				
			echo "Deconvolution Process Finished."
			cd  -
			
			if [ `ls $DATA_PATH/DISP/DISPL* | wc -l` -ge "12" ]; then 
				echo "$EVID Data is Ready to be Processed."
				echo "${DATA_PATH##*/}" >> .ready_data
			else
				echo "Sorry, $EVEID Data is less than our limits. Ignored ..."
			fi
		else
			echo "Event ($EVID) is outside of $Country boundaries. Ignored ... "
		fi
	done
	echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#"
}	

cd $KIWI_HOME
while true; do

	T1=`date -u --date="$TIME1 minutes ago" "+%Y-%m-%d %H:%M:%S"`
	T2=`date -u --date="$TIME2 minutes ago" "+%Y-%m-%d %H:%M:%S"`
	TN=`date -u "+%Y-%m-%d %H:%M:%S"`
	echo -e "Program Started Processing at ******* $TN ******* \n"
	GET_EVE_INFO & sleep "$sleep"
	
done 
